---
- name: Copying over neutron.conf
  vars:
    service_name: "{{ item.key }}"
    services_need_neutron_conf:
      - "neutron-dhcp-agent"
      - "neutron-l3-agent"
      - "neutron-linuxbridge-agent"
      - "neutron-metadata-agent"
      - "neutron-openvswitch-agent"
      - "neutron-server"
      - "neutron-lbaas-agent"
      - "neutron-vpnaas-agent"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/neutron.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/database.conf"
      - "{{ node_custom_config }}/messaging.conf"
      - "{{ node_custom_config }}/neutron.conf"
      - "{{ node_custom_config }}/neutron/{{ item.key }}.conf"
      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/neutron.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/neutron.conf"
  register: neutron_confs
  when:
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
    - item.key in services_need_neutron_conf
  with_dict: "{{ neutron_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over opencontrail_plugin.ini
  vars:
    service_name: "neutron-server"
    neutron_server: "{{ neutron_services[service_name] }}"
  template:
    src: "{{ role_path }}/templates/neutron_opencontrail.conf.j2"
    dest: "{{ node_config_directory }}/{{ service_name }}/ContrailPlugin.ini"
  register: neutron_opencontrail_conf
  when:
    - neutron_server.enabled | bool
    - neutron_server.host_in_groups | bool
  notify:
    - "Restart {{ service_name }} container"

- name: "Copying over ml2_conf.ini {{ neutron_opencontrail_conf }}"
  vars:
    service_name: "{{ item.key }}"
    services_need_ml2_conf_ini:
      - "neutron-linuxbridge-agent"
      - "neutron-openvswitch-agent"
      - "neutron-server"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/ml2_conf.ini.j2"
      - "{{ node_custom_config }}/neutron/ml2_conf.ini"
      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/ml2_conf.ini"
    dest: "{{ node_config_directory }}/{{ service_name }}/ml2_conf.ini"
  register: neutron_ml2_confs
  when:
    - item.key in services_need_ml2_conf_ini
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ neutron_services }}"
  notify:
    - "Restart {{ item.key }} container"

- include: config_opencontrail.yml
