---
- name: Copying over ContrailPlugin.ini
  vars:
    service_name: "neutron-server"
    neutron_server: "{{ neutron_services[service_name] }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/ContrailPlugin.ini.j2"
      - "{{ node_custom_config }}/neutron/ContrailPlugin.ini"
      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/ContrailPlugin.ini"
    dest: "{{ node_config_directory }}/{{ service_name }}/ContrailPlugin.ini"
  register: contrailplugin_ini
  when:
    - neutron_server.enabled | bool
    - neutron_server.host_in_groups | bool
    - neutron_plugin_agent == 'opencontrail'
  notify:
    - "Restart {{ service_name }} container"
