---
- name: Ensuring config directories exist
  file:
    path: "{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "{{ node_config_directory }}/ironic-notification-manager"
    - "/var/log/contrail"
    - "/etc/contrail"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "ironic-notification-manager"

- name: Copying over ironic-notification-manager.conf and contrail-keystone-auth.conf
  template:
    src: "{{ item }}.conf.j2"
    dest: "{{ node_config_directory }}/{{ item }}.conf"
  with_items:
    - "ironic-notification-manager"
    - "contrail-keystone-auth"

