---
- name: Copying over local_settings
  vars:
    horizon: "{{ horizon_services['horizon'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/horizon/local_settings"
  with_first_found:
    - "{{ node_custom_config }}/horizon/{{ inventory_hostname }}/local_settings"
    - "{{ node_custom_config }}/horizon/local_settings"
    - "local_settings.j2"
  register: horizon_local_settings
  when:
    - horizon.enabled | bool
    - inventory_hostname in groups[horizon.group]
  notify:
    - Restart horizon container
