---
- name: Copying over contrail certificates
  vars:
    service: "{{ haproxy_services['haproxy'] }}"
  copy:
    src: "{{ contrail_ca_file }}"
    dest: "{{ node_config_directory }}/haproxy/contrail-ca-cert.pem"
    mode: "0660"
  become: true
  when:
    - config_api_ssl_enable is defined
    - config_api_ssl_enable | bool
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart haproxy container
    - Ensuring latest haproxy config is used

