---
- name: convert disk_partition to disk_list
  set_fact:
    disk_list: "{{ disk_partition.replace(',',' ') }}"
  when: disk_partition is defined

- name: create template for disk partitioning script
  template:
    src: swift-create-disk-partition.sh.j2
    dest: /bin/swift_create_disk_partition.sh
    mode: 0755

- name: Creating block devices for swift storage
  command: /bin/swift_create_disk_partition.sh

- name: convert openstack_list to node_list
  set_fact:
    swift_node_list: "{{ groups['control']|join(' ') }}"
  when: storage_nodes is not defined

- name: convert storage_nodes to node_list
  set_fact:
    swift_node_list: "{{ storage_nodes.replace(',',' ') }}"
  when: storage_nodes is defined

- name: create template for ring builder script
  template:
    src: swift-ring-builder.sh.j2
    dest: /bin/swift_ring_builder.sh
    mode: 0755

- name: Creating swift rings
  command: /bin/swift_ring_builder.sh
