---
- hosts: all
  tasks:
  - name: Import variables
    include_vars:
      dir: ../etc/kolla
      extensions: ['yml']
      ignore_files:
        - passwords.yml.original
        - globals.yml.original

- name: Evaluate contrail version from image tag
  set_fact:
    contrail_version: "{{ neutron_opencontrail_init_image_full | get_contrail_version }}"

- include: kolla-host.yml
  vars:
    action: bootstrap-servers

- include: site.yml
  vars:
    action: deploy

- include: post-deploy.yml
  vars:
    action: deploy

- include: post-deploy-contrail.yml
  vars:
    action: deploy
