---
- name: Post-deploy playbook for contrail
  hosts: control
  tasks:

  - name: Creating admin openrc file for kolla-toolbox
    template:
      src: "roles/common/templates/admin-openrc.sh.j2"
      dest: "{{ node_config_directory }}/kolla-toolbox/admin-openrc.sh"

  - name: Disable the nova-compute on the openstack container
    command: >
      docker exec kolla_toolbox openstack
      --os-interface internal
      --os-auth-url {{ keystone_admin_url }}
      --os-identity-api-version 3
      --os-project-domain-name default
      --os-tenant-name admin
      --os-username admin
      --os-password {{ keystone_admin_password }}
      --os-user-domain-name default
      compute service set  --disable {{ hostvars[item].ansible_hostname }} nova-compute
    when:
      - enable_nova_compute | bool
      - disable_nova_compute_service | bool
      - hostvars[item].TSN_EVPN_MODE is defined
      - hostvars[item]['TSN_EVPN_MODE'] | bool
    with_items: "{{ groups['compute'] }}"
    tags: always

  ## Need to create Host Aggregates to separate Baremetal and Virtual Hosts
  - name: Create Host Aggregates to separate types of hosts
    command: >
      docker exec kolla_toolbox openstack
      --os-interface internal
      --os-auth-url {{ keystone_admin_url }}
      --os-identity-api-version 3
      --os-project-domain-name default
      --os-tenant-name admin
      --os-username admin
      --os-password {{ keystone_admin_password }}
      --os-user-domain-name default
      aggregate create --property baremetal={{ item.0 }} --zone {{ item.1 }} {{ item.2 }}
    with_together:
      - ['true', 'false']
      - ['nova-baremetal', 'nova']
      - ['baremetal-hosts', 'virtual-hosts']
    run_once: yes

  - name: Add compute hosts to virtual-hosts Aggregate Group
    command: >
      docker exec kolla_toolbox openstack
      --os-interface internal
      --os-auth-url {{ keystone_admin_url }}
      --os-identity-api-version 3
      --os-project-domain-name default
      --os-tenant-name admin
      --os-username admin
      --os-password {{ keystone_admin_password }}
      --os-user-domain-name default
      aggregate add host virtual-hosts {{ hostvars[item].ansible_hostname }}
    when:
      - hostvars[item].TSN_EVPN_MODE is defined
      - not hostvars[item]['TSN_EVPN_MODE'] | bool
    with_items: "{{ groups['compute'] }}"
    run_once: yes

  - name: Add controller/Ironic hosts to baremetal-hosts Aggregate Group
    command: >
      docker exec kolla_toolbox openstack
      --os-interface internal
      --os-auth-url {{ keystone_admin_url }}
      --os-identity-api-version 3
      --os-project-domain-name default
      --os-tenant-name admin
      --os-username admin
      --os-password {{ keystone_admin_password }}
      --os-user-domain-name default
      aggregate add host baremetal-hosts {{ hostvars[item].ansible_hostname }}-ironic
    with_items: "{{ groups['control'] }}"
    when:
      - enable_ironic | bool
    run_once: yes

  - name: Run simple cell setup if required
    include: roles/nova/tasks/simple_cell_setup.yml
    when: not enable_nova_compute | bool
    tags: always

    ## FIXME: This does not work for some reason!!
    #- name: Run simple cell setup if required
    #  include_role:
    #    name: nova
    #    tasks_from: simple_cell_setup
    #  when: not enable_nova_compute | bool


  - name: Contrail default swift container and Temp-URL-Key creation
    shell: docker exec kolla_toolbox bash -c 'source /var/lib/kolla/config_files/admin-openrc.sh; swift post -r '.r:*' contrail_container; swift post -m "Temp-URL-Key:mykey"'
    when:
      - enable_swift_opencontrail | bool
      - enable_swift | bool
    run_once: yes

- name: Post-deploy playbook for external services
  hosts: localhost
  tasks:
  - name: create openstack kolla external dir
    file:
      path: "{{ node_config_directory }}/external/"
      state: directory
      recurse: yes

  - name: Creating admin openrc file for external services
    template:
      src: "roles/common/templates/admin-openrc.yml.j2"
      dest: "{{ node_config_directory }}/external/admin-openrc.yml"
