---
- name: Post-deploy playbook for contrail
  hosts: control
  tasks:
  - name: Install prerequisites to install openstack clients
    yum:
      name: "{{ item }}"
      state: latest
    ignore_errors: yes
    with_items:
      - gcc
      - python-devel

  - name: Install python clients for openstack components
    pip:
      name: "{{ item }}"
      state: latest
    ignore_errors: yes
    with_items:
      - python-openstackclient
      - python-heatclient
      - python-ironicclient

  - name: Disable the nova-compute on the openstack container
    shell: . /etc/kolla/admin-openrc.sh && nova service-disable {{ ansible_hostname }} nova-compute
    ignore_errors: yes
    when: 
      - enable_nova_compute | bool
      - disable_nova_compute_service | bool

  - name: Run simple cell setup if required
    include: roles/nova/tasks/simple_cell_setup.yml
    when: not enable_nova_compute | bool

    ## FIXME: This does not work for some reason!!
    #- name: Run simple cell setup if required
    #  include_role:
    #    name: nova
    #    tasks_from: simple_cell_setup
    #  when: not enable_nova_compute | bool

  - name: Workaround for https://bugs.launchpad.net/bugs/1672741
    shell: docker exec horizon sed -i -e 's:/usr/share/openstack-dashboard/static:/var/lib/openstack-dashboard/static:g' /etc/apache2/conf-enabled/000-default.conf && docker exec horizon service apache2 reload
    ignore_errors: yes
    when: openstack_release == '4.0.0'
