---
- name: Post-deploy playbook for contrail
  hosts: control
  tasks:

  - name: Creating admin openrc file for kolla-toolbox
    template:
      src: "roles/common/templates/admin-openrc.sh.j2"
      dest: "{{ node_config_directory }}/kolla-toolbox/admin-openrc.sh"

  - name: Disable the nova-compute on the openstack container
    command: >
      docker exec kolla_toolbox openstack
      --os-interface internal
      --os-auth-url {{ keystone_admin_url }}
      --os-identity-api-version 3
      --os-project-domain-name default
      --os-tenant-name admin
      --os-username admin
      --os-password {{ keystone_admin_password }}
      --os-user-domain-name default
      compute service set  --disable {{ hostvars[item].ansible_hostname }} nova-compute
    when:
      - enable_nova_compute | bool
      - disable_nova_compute_service | bool
      - hostvars[item].TSN_EVPN_MODE is defined
      - hostvars[item]['TSN_EVPN_MODE'] | bool
    with_items: "{{ groups['compute'] }}"
    tags: always

  - name: Run simple cell setup if required
    include: roles/nova/tasks/simple_cell_setup.yml
    when: not enable_nova_compute | bool
    tags: always

    ## FIXME: This does not work for some reason!!
    #- name: Run simple cell setup if required
    #  include_role:
    #    name: nova
    #    tasks_from: simple_cell_setup
    #  when: not enable_nova_compute | bool


  - name: Contrail default swift container and Temp-URL-Key creation
    shell: docker exec kolla_toolbox bash -c 'source /var/lib/kolla/config_files/admin-openrc.sh; swift post -r '.r:*' contrail_container; swift post -m "Temp-URL-Key:mykey"'
    when:
      - enable_swift_opencontrail | bool
      - enable_swift | bool
    run_once: yes
