---

- name: Get disabled services
  shell: >
    docker exec kolla_toolbox openstack
    --os-interface internal
    --os-auth-url {{ keystone_admin_url }}
    --os-identity-api-version 3
    --os-project-domain-name default
    --os-tenant-name admin
    --os-username admin
    --os-password {{ keystone_admin_password }}
    --os-user-domain-name default
    compute service list | grep {{ hostvars[item].instance_name }} | awk '{print $2}'
  with_items: "{{ hostvars[inventory_hostname].groups.compute }}"
  run_once: yes
  register: nova_services

- debug:
    var: nova_services.results

- name: Disable the nova-compute on the openstack container
  command: >
    docker exec kolla_toolbox openstack
    --os-interface internal
    --os-auth-url {{ keystone_admin_url }}
    --os-identity-api-version 3
    --os-project-domain-name default
    --os-tenant-name admin
    --os-username admin
    --os-password {{ keystone_admin_password }}
    --os-user-domain-name default
    compute service set 
    --disable-reason "Removing compute"
    --disable {{ hostvars[item.0].instance_name }} nova-compute
  with_together: 
    - "{{ hostvars[inventory_hostname].groups.compute }}"
    - "{{ nova_services.results }}" 
  run_once: yes
  when: item.1.stdout

## Need to create Host Aggregates to separate Baremetal and Virtual Hosts
- name: Remove compute hosts from virtual-hosts Aggregate Group
  command: >
    docker exec kolla_toolbox openstack
    --os-interface internal
    --os-auth-url {{ keystone_admin_url }}
    --os-identity-api-version 3
    --os-project-domain-name default
    --os-tenant-name admin
    --os-username admin
    --os-password {{ keystone_admin_password }}
    --os-user-domain-name default
    aggregate remove host virtual-hosts {{ hostvars[item.0].instance_name }}
  when:
    - hostvars[item.0].TSN_EVPN_MODE is defined
    - not hostvars[item.0]['TSN_EVPN_MODE'] | bool
    - item.1.stdout
  with_together:
    - "{{ hostvars[inventory_hostname].groups.compute }}"
    - "{{ nova_services.results }}"
  run_once: yes

- name: Get disabled services 
  shell: >
    docker exec kolla_toolbox openstack
    --os-interface internal
    --os-auth-url {{ keystone_admin_url }}
    --os-identity-api-version 3
    --os-project-domain-name default
    --os-tenant-name admin
    --os-username admin
    --os-password {{ keystone_admin_password }}
    --os-user-domain-name default
    compute service list | grep {{ hostvars[item].instance_name }} | awk '{print $2}'
  with_items: "{{ hostvars[inventory_hostname].groups.compute }}"
  run_once: yes
  register: disabled_nova_services

- debug:
    var: disabled_nova_services.results

- name: Remove the disabled services
  command: >
    docker exec kolla_toolbox openstack
    --os-interface internal
    --os-auth-url {{ keystone_admin_url }}
    --os-identity-api-version 3
    --os-project-domain-name default
    --os-tenant-name admin
    --os-username admin
    --os-password {{ keystone_admin_password }}
    --os-user-domain-name default
    compute service delete {{ item.stdout }}
  with_items: "{{ disabled_nova_services.results }}"
  run_once: yes
  when: item.stdout
  register: disabled_nova_services
