---
- name: Copying over heat.conf
  merge_configs:
    vars:
      service_name: "{{ item.key }}"
    sources:
      - "{{ role_path }}/templates/heat.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/database.conf"
      - "{{ node_custom_config }}/messaging.conf"
      - "{{ node_custom_config }}/heat.conf"
      - "{{ node_custom_config }}/heat/{{ item.key }}.conf"
      - "{{ node_custom_config }}/heat/{{ inventory_hostname }}/heat.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/heat.conf"
  register: heat_confs
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ heat_services }}"
  notify:
    - Restart heat-api container
    - Restart heat-api-cfn container
    - Restart heat-engine container
